version: "3.9"

services:
  db:
    image: postgres:17
    restart: always
    container_name: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "${PORT:-7001}:${PORT:-7001}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      pgadmin:
        condition: service_started
    volumes:
      - ./:/app
      - /app/node_modules
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma generate &&
        npm run start:dev
      "
